auto: true
server: true
permalink: none
baseurl: ""
exclude:
- .gitignore
- README.md
prose:
  rooturl: "_posts"
  metadata:
    "_posts/projects":
      - name: "categories"
        field:
          element: "select"
          label: "Category"
          placeholder: "Select category"
          options:
            - name: "projects"
              value: "Project"
      - name: "subjects"
        field:
          element: "multiselect"
          label: "Subjects"
          placeholder: "Select an Item"
          options:
            - name: "Animation"
              value: "Animation"
            - name: "Visual Effects"
              value: "Visual Effets"
            - name: "3D Modelling"
              value: "3D Modelling"
          selected: "Animation"
      - name: "name"
        field:
          element: "text"
          label: "Project Title"
          value: "My Project Title"
      - name: "creator"
        field:
          element: "text"
          label: "Project Creator"
          value: "John Doe"
      - name: "abstract"
        field:
          element: "text"
          label: "Project Summary"
          value: "Enter a short description of your project"
      - name: "image"
        field:
          element: "text"
          label: "Image URL"
          value: "http://f.cl.ly/items/1o363t351s47371R3X2f/polished-off.png"
      - name: "website"
        field:
          element: "text"
          label: "Website URL"
          value: "http://www.rave.co.uk/"
